---
abstract: 'check a modules you are installed'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Advisor
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Module::Advisor:
    file: lib/Module/Advisor.pm
    version: 0.17
requires:
  CPAN::Meta::Requirements: 2.122
  Module::Metadata: 1.000000
  parent: 0
  perl: 5.008008
resources:
  bugtracker: https://github.com/tokuhirom/Module-Advisor/issues
  homepage: https://github.com/tokuhirom/Module-Advisor
  repository: git://github.com/tokuhirom/Module-Advisor.git
version: 0.17
x_contributors:
  - 'Daisuke Murase <typester@cpan.org>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
